name: CI Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test || echo "No tests defined" | tee build.log
    - name: Save build logs
      run: |
        echo "Build completed at $(date)" >> build.log
        mv build.log logs/build-$(date +%F-%H-%M-%S).log
    - name: Commit build logs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add logs/
        git commit -m "Add build log" || echo "No changes to commit"
        git push